# Generated by Django 5.0.4 on 2025-10-12 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('contenido', models.TextField()),
                ('resumen', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='blog.categoria')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulo',
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
                'indexes': [models.Index(fields=['publicado'], name='articulo_publica_f53dc7_idx'), models.Index(fields=['slug'], name='articulo_slug_1d29b5_idx'), models.Index(fields=['autor'], name='articulo_autor_i_9d8dd0_idx'), models.Index(fields=['categoria'], name='articulo_categor_ae1160_idx')],
            },
        ),
    ]
