# Generated by Django 5.2.6 on 2025-10-26 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_respondidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacto',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='contact.estado'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_asunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='contact.tipoasunto'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['activa'], name='suscripcion_activa_c84bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['email'], name='suscripcion_email_845b19_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['estado'], name='contacto_estado__959b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['fecha_envio'], name='contacto_fecha_e_706e67_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['usuario'], name='contacto_usuario_5c30c0_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['tipo_asunto'], name='contacto_tipo_as_8e5dcb_idx'),
        ),
    ]
