# Generated by Django 5.0.4 on 2025-10-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoasunto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
