# Generated by Django 5.2.6 on 2025-10-26 17:07

import apps.articulos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('resumen', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('imagen_portada', models.ImageField(blank=True, help_text='Imagen horizontal para modal/detalle (1200x400px recomendado)', null=True, upload_to=apps.articulos.models.upload_to_articulos_imagen, verbose_name='Imagen Banner (Horizontal)')),
                ('imagen_thumbnail', models.ImageField(blank=True, help_text='Imagen cuadrada para tarjetas de lista (600x600px recomendado)', null=True, upload_to=apps.articulos.models.upload_to_articulos_imagen, verbose_name='Imagen Miniatura (Cuadrada)')),
                ('imagen_url', models.URLField(blank=True, help_text='Alternativa: URL de imagen externa (se usa si no hay imagen subida)', max_length=500, null=True, verbose_name='URL de imagen externa')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, etc. (opcional)', null=True, verbose_name='URL de video')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='PDF, Word, Excel, etc. (opcional, máx 10MB)', null=True, upload_to=apps.articulos.models.upload_to_articulos_archivo, verbose_name='Archivo adjunto')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('vistas', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulo',
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentario_articulo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
