# Generated by Django 5.2.6 on 2025-10-26 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='articulos.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='comentarioarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='articulos.articulo'),
        ),
        migrations.AddField(
            model_name='comentarioarticulo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_articulos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['publicado'], name='articulo_publica_f53dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['slug'], name='articulo_slug_1d29b5_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['autor'], name='articulo_autor_i_9d8dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['categoria'], name='articulo_categor_ae1160_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['-fecha_publicacion'], name='articulo_fecha_p_111db5_idx'),
        ),
    ]
