# Generated by Django 5.0.4 on 2025-10-18 15:19

import apps.articulos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_add_multimedia_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen_thumbnail',
            field=models.ImageField(blank=True, help_text='Imagen cuadrada para tarjetas de lista (600x600px recomendado)', null=True, upload_to=apps.articulos.models.upload_to_articulos_imagen, verbose_name='Imagen Miniatura (Cuadrada)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen_portada',
            field=models.ImageField(blank=True, help_text='Imagen horizontal para modal/detalle (1200x400px recomendado)', null=True, upload_to=apps.articulos.models.upload_to_articulos_imagen, verbose_name='Imagen Banner (Horizontal)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Alternativa: URL de imagen externa (se usa si no hay imagen subida)', max_length=500, null=True, verbose_name='URL de imagen externa'),
        ),
    ]
