# Generated by Django 5.0.4 on 2025-10-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionradio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la estación está transmitiendo actualmente', verbose_name='En el aire'),
        ),
    ]
