# Generated by Django 5.2.6 on 2025-10-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('radio', '0001_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandaIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Banda-Integrante',
                'verbose_name_plural': 'Bandas-Integrantes',
                'db_table': 'banda_integrante',
            },
        ),
        migrations.CreateModel(
            name='BandaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Link de Banda',
                'verbose_name_plural': 'Links de Bandas',
                'db_table': 'banda_link',
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'db_table': 'integrante',
            },
        ),
        migrations.CreateModel(
            name='BandaEmergente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banda', models.CharField(max_length=150)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.TextField()),
                ('documento_presentacion', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandas_emergentes', to='ubicacion.comuna')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandas_emergentes', to='contact.estado')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandas_emergentes', to='radio.generomusical')),
            ],
            options={
                'verbose_name': 'Banda Emergente',
                'verbose_name_plural': 'Bandas Emergentes',
                'db_table': 'banda_emergente',
            },
        ),
    ]
