# Generated by Django 5.2.6 on 2025-10-26 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bandaemergente',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandas_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bandaemergente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandas_emergentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bandaintegrante',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='emergente.bandaemergente'),
        ),
        migrations.AddField(
            model_name='bandalink',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='emergente.bandaemergente'),
        ),
        migrations.AddField(
            model_name='bandaintegrante',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandas', to='emergente.integrante'),
        ),
        migrations.AddIndex(
            model_name='bandaemergente',
            index=models.Index(fields=['estado'], name='banda_emerg_estado__abbc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='bandaemergente',
            index=models.Index(fields=['genero'], name='banda_emerg_genero__7e40b0_idx'),
        ),
        migrations.AddIndex(
            model_name='bandaemergente',
            index=models.Index(fields=['usuario'], name='banda_emerg_usuario_9ea2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='bandaemergente',
            index=models.Index(fields=['comuna'], name='banda_emerg_comuna__d287e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bandaintegrante',
            unique_together={('banda', 'integrante')},
        ),
    ]
