# Generated by Django 5.0.4 on 2025-10-12 15:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('WEB', 'Web'), ('RADIAL', 'Radial')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('archivo_media', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
                'db_table': 'publicidad',
            },
        ),
        migrations.CreateModel(
            name='PublicidadRadial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_segundos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_por_segundo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicidades', to='radio.horarioprograma')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicidades', to='radio.programa')),
                ('publicidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radial_config', to='publicidad.publicidad')),
            ],
            options={
                'verbose_name': 'Publicidad Radial',
                'verbose_name_plural': 'Publicidades Radiales',
                'db_table': 'publicidad_radial',
            },
        ),
        migrations.CreateModel(
            name='PublicidadWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(choices=[('banner_superior', 'Banner Superior'), ('lateral', 'Lateral'), ('footer', 'Footer')], max_length=50)),
                ('formato', models.CharField(blank=True, max_length=50, null=True)),
                ('url_destino', models.URLField(blank=True, max_length=500, null=True)),
                ('impresiones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clics', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_por_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('publicidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_config', to='publicidad.publicidad')),
            ],
            options={
                'verbose_name': 'Publicidad Web',
                'verbose_name_plural': 'Publicidades Web',
                'db_table': 'publicidad_web',
            },
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['usuario'], name='publicidad_usuario_0bcea4_idx'),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['tipo'], name='publicidad_tipo_d3c5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['activo'], name='publicidad_activo_8d42af_idx'),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='publicidad_fecha_i_2360ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicidad',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='publicidad_fechas_validas'),
        ),
        migrations.AddIndex(
            model_name='publicidadradial',
            index=models.Index(fields=['programa'], name='publicidad__program_de8285_idx'),
        ),
        migrations.AddIndex(
            model_name='publicidadradial',
            index=models.Index(fields=['horario'], name='publicidad__horario_0c7320_idx'),
        ),
    ]
