# Generated by Django 5.2.6 on 2025-10-26 17:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('WEB', 'Web'), ('RADIAL', 'Radial')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('archivo_media', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
                'db_table': 'publicidad',
            },
        ),
        migrations.CreateModel(
            name='PublicidadRadial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_segundos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_por_segundo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Publicidad Radial',
                'verbose_name_plural': 'Publicidades Radiales',
                'db_table': 'publicidad_radial',
            },
        ),
        migrations.CreateModel(
            name='PublicidadWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(choices=[('banner_superior', 'Banner Superior'), ('lateral', 'Lateral'), ('footer', 'Footer')], max_length=50)),
                ('formato', models.CharField(blank=True, max_length=50, null=True)),
                ('url_destino', models.URLField(blank=True, max_length=500, null=True)),
                ('impresiones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clics', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_por_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Publicidad Web',
                'verbose_name_plural': 'Publicidades Web',
                'db_table': 'publicidad_web',
            },
        ),
    ]
