# Generated by Django 5.0.4 on 2025-10-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0001_initial'),
    ]

    operations = [
    ]
