# Generated by Django 5.2.6 on 2025-10-26 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicidad', '0001_initial'),
        ('radio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicidadradial',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicidades', to='radio.horarioprograma'),
        ),
        migrations.AddField(
            model_name='publicidadradial',
            name='publicidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radial_config', to='publicidad.publicidad'),
        ),
        migrations.AddField(
            model_name='publicidadweb',
            name='publicidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_config', to='publicidad.publicidad'),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['usuario'], name='publicidad_usuario_0bcea4_idx'),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['tipo'], name='publicidad_tipo_d3c5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['activo'], name='publicidad_activo_8d42af_idx'),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='publicidad_fecha_i_2360ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicidad',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='publicidad_fechas_validas'),
        ),
        migrations.AddIndex(
            model_name='publicidadradial',
            index=models.Index(fields=['horario'], name='publicidad__horario_0c7320_idx'),
        ),
    ]
