# Generated by Django 5.0.4 on 2025-10-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0002_remove_programa_from_publicidad_radial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publicidadradial',
            name='publicidad__program_de8285_idx',
        ),
        migrations.RemoveField(
            model_name='publicidadradial',
            name='programa',
        ),
    ]
